# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unpack-deb-package:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Run in debian docker container
    container: debian:12
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Update package info and install wget
        run: apt update && apt install -y wget

      - name: Download latest lantern .deb package file
        run: wget https://s3.amazonaws.com/lantern/lantern-installer-64-bit.deb

      - name: Extract .deb Lantern file
        run: dpkg-deb -x lantern-installer-64-bit.deb /lantern && dpkg -e lantern-installer-64-bit.deb /lantern

      - name: Save to cache extracted files
        uses: actions/cache/save@v3
        with:
          path: /lantern
          key: unpacked-lantern

  arch-package-build:
    runs-on: ubuntu-22.04
    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v4

      - name: Build archlinux package
        uses: py7hon/arch-makepkg@v0.0.2

      - uses: actions/upload-artifact@v3
        with:
          path: lantern-7.4.0-1-x86_64.pkg.tar.zst